#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 1 
#define MY_DISP_HOR_RES 240
#define MY_DISP_VER_RES 300

#define LV_USE_PERF_MONITOR_POS
#define CONFIG_LV_USE_PERF_MONITOR_POS

#endif